### ISSUE TITLE
Updated depdencies?

### ISSUE THREAD

**Issue by EduardoFromTheFuture** [boydaihungst/vue-enterprise-boilerplate#33]
The vue-enterprise-boilerplate repository is recommended in many places for being an amazing template to start building. However it's now based on old dependencies.

This fork is the one with the most recent dependencies, but it's still old for nowadays. There are even braking changes, like upgrading from vuex to pinia

Are there any plans to update the dependencies?

**Comment by boydaihungst** [comment]
Sorry for making you wait so long. I forgot to watch this repo. I just update to the newest dependencies. Changed codebase to suite the test. You can check it in here #47 
But I didn't have too much time to update all the doc files.
